# Arxiv categories to fetch
category = [
    "cs",
    "stat",
]

[ArxivOAI]
base_url = "https://oaipmh.arxiv.org/oai"
metadata_prefix = "arXiv" # Changed from oai_dc
request_delay_seconds = 3
retry_delay_seconds = 60
max_retries = 5
batch_size = 1000

[Embedding]
[Embedding.jasper_v1]
model_name = "NovaSearch/jasper_en_vision_language_v1"
dimension = 1024

[Embedding.conan_v1]
model_name = "TencentBAC/Conan-embedding-v1"
dimension = 1792

