name: Daily Arxiv Incremental Update

on:
  schedule:
    # 每天凌晨 2:30 UTC (对应北京时间 10:30) 运行
    - cron: '30 2 * * *'
  # 允许手动触发
  workflow_dispatch:

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Fetch and update Arxiv data
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          python script/incremental_embed_workflow.py --days 2 --repo-id lyk/ArxivEmbedding
      
      - name: Trigger batch embedding workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Batch Embed
          token: ${{ secrets.GITHUB_TOKEN }}